SELECT * FROM T_ND_TABLE_MAPPING;
SELECT * FROM T_ND_TABLE_MAPPING FOR UPDATE;
TRUNCATE TABLE T_ND_TABLE_MAPPING;
UPDATE T_ND_TABLE_MAPPING T
   SET T.CREATE_TIME =
       (SELECT DISTINCT CREATE_TIME
          FROM T_ND_TABLE_MAPPING A
         WHERE A.CREATE_TIME IS NOT NULL)
 WHERE T.CREATE_TIME IS NULL;
 alter table T_ND_TABLE_MAPPING rename column code to ND_CODE;
alter table T_ND_TABLE_MAPPING rename column name to ND_NAME;
alter table T_ND_TABLE_MAPPING rename column type to ND_TYPE;
