SELECT * FROM T_ND_REL;
SELECT * FROM T_ND_REL FOR UPDATE;
TRUNCATE TABLE T_ND_REL;
UPDATE T_ND_REL T
	 SET T.CREATE_TIME =
			 (SELECT DISTINCT CREATE_TIME
					FROM T_ND_REL A
				 WHERE A.CREATE_TIME IS NOT NULL)
 WHERE T.CREATE_TIME IS NULL;
SELECT (SELECT B.ND_NAME FROM T_ND B WHERE B.ID = A.PARENT_ID) ND_NAME,
			 (SELECT B.ND_NAME FROM T_ND B WHERE B.ID = A.CHILDND_ID) ND_NAME,
			 (SELECT B.DESCRIPT FROM T_ND B WHERE B.ID = A.PARENT_ID) DESCRIPT,
			 (SELECT B.DESCRIPT FROM T_ND B WHERE B.ID = A.CHILDND_ID) DESCRIPT
	FROM T_ND_REL A
 START WITH PARENT_ID = 101
CONNECT BY PRIOR A.CHILDND_ID = A. PARENT_ID
 ORDER BY A.PARENT_ID;
