SELECT * FROM T_ND_FD;
SELECT * FROM T_ND_FD FOR UPDATE;
TRUNCATE TABLE T_ND_FD;
UPDATE T_ND_FD T
	 SET T.CREATE_TIME =
			 (SELECT DISTINCT CREATE_TIME
					FROM T_ND_FD A
				 WHERE A.CREATE_TIME IS NOT NULL)
 WHERE T.CREATE_TIME IS NULL;
